### ISSUE TITLE
updating to spark 3 and xgb 1.3.1

### ISSUE THREAD

**Issue by Data-drone** [rstudio/sparkxgb#29]
any tips on how to update this for Spark 3 and xgb 1.3.1

**Comment by Data-drone** [comment]
@yitao-li as I commented in your previous merge, I tried to follow your script but hit issues

**Comment by yitao-li** [comment]
@Data-drone Everything built successfully on my side. FYI this build process is dependent on `sparklyr`, so maybe updating your local copy of `sparklyr` to the most recent version (namely, version 1.5) will help.

**Comment by yitao-li** [comment]
@Data-drone Alright all required changes for working with Spark 3 + xgb 1.3.1 are on the way to CRAN now. They will soon be available as part of sparkxgb 0.1.1.
